export default {
  index: {
    display: "hidden",
  },
  "-- Introduction": {
    title: "Introduction",
    type: "separator",
  },
  overview: "Overview",
  why_c: "Why C?",
  history: "History of C",

  "-- Getting Started": {
    title: "Getting Started",
    type: "separator",
  },
  setup: "Setting up Environment",
  ide_intro: "Introduction to IDE",
  compile_run: "Compiling and Running",
  "-- fundamentals": {
    title: "Fundamentals",
    type: "separator",
  },
  program_structure: "Program Structure",
  data_types: "Data Types",
  variables: "Variables",
  in_output: "Input & Output",
  type_convertion: "Type Conversion",
  "--operators": {
    title: "Operators",
    type: "separator",
  },
  arithmetic_operators: "Arithmetic Operators",
  relational_and_logical: "Relational and Logical Operators",
  assignment_operators: "Assignment Operators",
  increment_decrement: "Increment and Decrement Operators",
  bitwise_operators: "Bitwise Operators",

  "--control-flow": {
    title: "Control Structures",
    type: "separator",
  },
  conditional_statements: "Conditional Statements",
  nested_conditions: "Nested Conditions",
  switch_statements: "Switch Statements",
  loops_intro: "Loops & Iterations",
  for_loop: "For Loop",
  while_loop: "While Loop",
  do_while_loop: "Do-While Loop",
  nested_loops: "Nested Loops",
  break_continue: "Break and Continue",
  "--functions": {
    title: "Functions",
    type: "separator",
  },
  functions_intro: "Introduction to Functions",
  function_definition: "Function Definition",
  function_parameters: "Function Parameters",
  return_values: "Return Values",
  scope_of_variables: "Scope of Variables",
  recursive_functions: "Recursive Functions",
  "--arrays": {
    title: "Arrays & Strings",
    type: "separator",
  },
  arrays_basics: "Arrays Basics",
  array_operations: "Array Operations",
  multi_dimensional_arrays: "Multi-Dimensional Arrays",
  strings: "Strings Basics",
  string_functions: "String Functions",
  "--pointers": {
    title: "Pointers & Memory Management",
    type: "separator",
  },
  pointers_intro: "Pointers Introduction",
  pointers_arithmetic: "Pointers Arithmetic",
  pointer_and_arrays: "Pointers and Arrays",
  dynamic_memory_allocation: "Dynamic Memory Allocation",
  pointers_to_functions: "Pointers to Functions",
  "--structures": {
    title: "Structures & Unions",
    type: "separator",
  },
  structures_intro: "Structures Introduction",
  nested_structures: "Nested Structures",
  array_of_structures: "Array of Structures",
  unions: "Unions",
  "--file_handling": {
    title: "File Handling",
    type: "separator",
  },
  file_handling_intro: "File Handling Introduction",
  file_operations: "File Operations",
  file_modes: "File Modes",
  error_handling: "Error Handling",
  advanced_file_handling: "Advanced File Handling",
  "--advanced": {
    title: "Advanced",
    type: "separator",
  },
  preprocessor_directives: "Preprocessor Directives",
  memory_management: "Memory Management",
  bitwise_operations: "Bitwise Operations",
  debugging_optimization: "Debugging & Optimization",
  "--references": {
    title: "References",
    type: "separator",
  },
  recommended_books: "Recommended Books",
  useful_links: "Useful Links",
};
