const meta = {
  // index: {
  //   display: "hidden",
  // },
  "-- Getting Started": {
    title: "Getting Started",
    type: "separator",
  },
  index: "Overview",
  why_c: "Why C?",
  history: "History of C",

  "-- Setup": {
    title: "Environment Setup",
    type: "separator",
  },
  setup: "Setting up Environment",
  ide_intro: "Introduction to IDE",
  compile_run: "Compiling and Running",
  "-- fundamentals": {
    title: "Fundamentals",
    type: "separator",
  },
  program_structure: "Program Structure",
  c_data_types: "Data Types",
  c_variables: "Variables",
  in_output: "Input & Output",
  type_convertion: "Type Conversion",
  "--operators": {
    title: "Operators",
    type: "separator",
  },
  c_arithmetic_operators: "Arithmetic Operators",
  c_relational_operators: "Relational Operators",
  c_logical_operators: "Logical Operators",
  c_assignment_operators: "Assignment Operators",
  c_increment_decrement: "Increment and Decrement",
  c_bitwise_operator: "Bitwise Operators",

  "--control-flow": {
    title: "Control Structures",
    type: "separator",
  },
  c_conditional_introduction: "Introduction",
  c_decision_statements: "Decision Statements",
  c_looping_statement: "Looping Statements",
  c_jump_statements: "Jump Statements",
  "--functions": {
    title: "Functions",
    type: "separator",
  },
  functions_intro: "Introduction to Functions",
  function_definition: "Function Definition",
  function_parameters: "Function Parameters",
  return_values: "Return Values",
  scope_of_variables: "Scope of Variables",
  recursive_functions: "Recursive Functions",
  "--arrays": {
    title: "Arrays & Strings",
    type: "separator",
  },
  arrays_basics: "Arrays Basics",
  array_initialization: "Array Initialization",
  array_memory_allocation: "Array Memory Allocation",
  array_operations: "Array Operations",
  passing_arrays_to_functions: "Passing Arrays to Functions",
  array_searching_and_sorting: "Array Searching and Sorting",
  multi_dimensional_arrays: "Multi-Dimensional Arrays",
  strings: "Strings Basics",
  string_functions: "String Functions",
  "--pointers": {
    title: "Pointers & Memory Management",
    type: "separator",
  },
  pointers_intro: "Pointers Introduction",
  pointers_arithmetic: "Pointers Arithmetic",
  pointer_and_arrays: "Pointers and Arrays",
  dynamic_memory_allocation: "Dynamic Memory Allocation",
  pointers_to_functions: "Pointers to Functions",
  "--structures": {
    title: "Structures & Unions",
    type: "separator",
  },
  structures_intro: "Structures Introduction",
  nested_structures: "Nested Structures",
  array_of_structures: "Array of Structures",
  unions: "Unions",
  "--file_handling": {
    title: "File Handling",
    type: "separator",
  },
  file_handling_intro: "File Handling Introduction",
  file_operations: "File Operations",
  file_modes: "File Modes",
  error_handling: "Error Handling",
  c_advanced_file_handling: "Advanced File Handling",
  "--advanced": {
    title: "Advanced",
    type: "separator",
  },
  preprocessor_directives: "Preprocessor Directives",
  memory_management: "Memory Management",
  debugging_optimization: "Debugging & Optimization",
  "--references": {
    title: "References",
    type: "separator",
  },
  recommended_books: "Recommended Books",
  useful_links: "Useful Links",
};

export default meta;
